apiVersion: v1
kind: Secret
metadata:
  name: jfrog-cred
  namespace: taxi
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJ0cmlhbHFyYmF6ay5qZnJvZy5pbyI6IHsKCQkJImF1dGgiOiAiWkc5amEyVnlPa1J2WTJ0bGNrQXhNak09IgoJCX0KCX0KfQ==
type: kubernetes.io/dockerconfigjson
